name: Releases

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  Images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build images
        run: |
          make build-image
      - name: Push images
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          OLD_REGISTRY=k8s.gcr.io REGISTRY="docker.pkg.github.com/$(echo ${{ github.repository }} | tr "A-Z" "a-z")" make push-image

  Server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build server binaries
        run: |
          make build-server
      - name: Push server binaries
        uses: wzshiming/action-upload-release-assets@v1
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE: release

  Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build client binaries
        run: |
          git config --global user.name "bot"
          make build-client
      - name: Push client binaries
        uses: wzshiming/action-upload-release-assets@v1
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE: release
