name: Releases Source

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependent
        run: |
          make dependent
      - name: Config Github
        run: |
          git config --global user.email "noreply@github.com"
          git config --global user.name "GitHub"
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Release source
        env:
          SOURCE: https://github.com/klts-io/kubernetes
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          make public-source
