name: Releases

on:
  push:
    tags:
      - v*

  workflow_dispatch:

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache workdir
        uses: actions/cache@v2
        env:
          cache-name: workdir
        with:
          path: workdir
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Verify patch
        run: |
          make $(basename ${GITHUB_REF})

  Images:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache workdir
        uses: actions/cache@v2
        env:
          cache-name: workdir
        with:
          path: workdir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-image
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build images
        run: |
          make build-image
      - name: Push images
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          OLD_REGISTRY=k8s.gcr.io REGISTRY="ghcr.io/$(echo ${{ github.repository }} | tr "A-Z" "a-z")" make push-image

  Server:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache workdir
        uses: actions/cache@v2
        env:
          cache-name: workdir
        with:
          path: workdir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-server
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build server binaries
        run: |
          make build-server
      - name: Push server binaries
        uses: wzshiming/action-upload-release-assets@v1
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE: release

  Client:
    needs: Patch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache workdir
        uses: actions/cache@v2
        env:
          cache-name: workdir
        with:
          path: workdir
          key: ${{ runner.os }}-build-${{ env.cache-name }}-server
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Install dependent
        run: |
          git config --global user.name "bot"
          make dependent
      - name: Checkout
        run: |
          make $(basename ${GITHUB_REF})
      - name: Build client binaries
        run: |
          git config --global user.name "bot"
          make build-client
      - name: Push client binaries
        uses: wzshiming/action-upload-release-assets@v1
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          RELEASE: release
