name: "Verify Patch"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run verify
        run: |
          git config --global user.name "bot"
          make dependent verify-patch
